# Generated by Django 4.2.7 on 2023-12-05 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0002_eventsschedule_speaker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventsschedule",
            name="Description",
        ),
        migrations.RemoveField(
            model_name="eventsschedule",
            name="title",
        ),
        migrations.RemoveField(
            model_name="eventsschedule",
            name="speaker",
        ),
        migrations.CreateModel(
            name="EventPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=225)),
                ("Description", models.TextField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_panel",
                        to="events.event",
                    ),
                ),
                (
                    "speaker",
                    models.ManyToManyField(
                        related_name="panel_speaker", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="eventsschedule",
            name="panel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="panel_schedule",
                to="events.eventpanel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventsschedule",
            name="speaker",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_speaker",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
