# Generated by Django 4.2.7 on 2023-12-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_analysis_rubric"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="Presentation",
            new_name="entries_header",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="executive_summary",
            new_name="presentation",
        ),
    ]
