# Generated by Django 4.2.7 on 2023-12-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_rename_presentation_event_entries_header_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpanel",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
