# Generated by Django 4.2.7 on 2023-12-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_eventsschedule_panel"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="final_date",
            field=models.DateField(default="2023-10-10"),
            preserve_default=False,
        ),
    ]
