# Generated by Django 4.2.7 on 2023-12-05 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0008_event_final_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsschedule",
            name="speaker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_speaker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
