# Generated by Django 4.2.7 on 2023-12-05 13:05

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0009_alter_eventsschedule_speaker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsteam",
            name="member",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="team_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="eventsteam",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_mentor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="eventsteam",
            name="white_paper",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FileField(
                    blank=True, null=True, upload_to="Event/TeamWhitePaper"
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
