# Generated by Django 4.2.7 on 2023-12-05 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0010_alter_eventsteam_member_alter_eventsteam_mentor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsteam",
            name="team_creator",
            field=models.ForeignKey(
                default="061c1b5a-b65b-4149-b9d2-964e2c1f2e5f",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_creator_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
