# Generated by Django 4.2.7 on 2023-12-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_eventsteam_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpanel',
            old_name='Description',
            new_name='description',
        ),
    ]
