# Generated by Django 4.2.7 on 2023-12-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_rename_description_eventpanel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsschedule',
            options={'ordering': ['-created_at']},
        ),
    ]
