# Generated by Django 4.2.7 on 2023-12-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpfulresources',
            name='file_type',
            field=models.CharField(choices=[('url', 'Url'), ('pdf', 'Pdf')], default='pdf', max_length=3),
        ),
        migrations.AddField(
            model_name='responsestrategies',
            name='file_type',
            field=models.CharField(choices=[('url', 'Url'), ('pdf', 'Pdf')], default='pdf', max_length=3),
        ),
        migrations.AddField(
            model_name='taprootcauses',
            name='file_type',
            field=models.CharField(choices=[('url', 'Url'), ('pdf', 'Pdf')], default='pdf', max_length=3),
        ),
    ]
