# Generated by Django 4.2.7 on 2023-12-07 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("repositorys", "0002_helpfulresources_file_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpactOnSociety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("url", "Url"), ("pdf", "Pdf")],
                        default="pdf",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ResearchRepository/ImpactOnSociety",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "research_repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impact_on_society",
                        to="repositorys.researchrepository",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
