# Generated by Django 4.2.7 on 2023-12-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='graduation_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academic',
            name='major',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='courses_taught',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='research_papers',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
